## Fundamentals

In [1]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
torch.cuda.get_device_name(0)

1.11.0


'NVIDIA GeForce GTX 1080 Ti'

## Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2308, 0.6156, 0.8955, 0.2103],
        [0.0623, 0.6378, 0.0012, 0.1127],
        [0.9210, 0.0377, 0.1841, 0.5451]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
one_to_ten = torch.arange(start= 0, end= 10, step=2)

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [23]:
float_32_tensor = torch.tensor([3.0, 6.0 , 9.0], dtype = torch.float16, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_32_tensor.dtype

torch.float16

In [25]:
float_32_tensor.device

device(type='cpu')

In [26]:
tensor = torch.tensor([1, 2 ,3 ])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor = torch.tensor([1, 2 ,3 ])
tensor * 10

tensor([10, 20, 30])

In [28]:
tensor = torch.tensor([1, 2 ,3 ])
tensor - 10

tensor([-9, -8, -7])

In [29]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [30]:
# Element Wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [31]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [32]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [8,11],
                        [12,3]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8, 12],
        [ 8, 11,  3]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  30,  18],
        [ 53,  68,  48],
        [ 83, 106,  78]])

In [ ]:
x = torch.arange(0,100,10)
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
import torch 
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped = x_reshaped.squeeze()

In [ ]:
x_reshaped.unsqueeze(dim=0)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2, 0 , 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[:, : , 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
import torch
import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [ ]:
array = array + 1
array, tensor

(array([3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [34]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2071, 0.4541, 0.3350, 0.7495],
        [0.8158, 0.8510, 0.7141, 0.2792],
        [0.8756, 0.2726, 0.5003, 0.0957]])
tensor([[0.7742, 0.9097, 0.3837, 0.3309],
        [0.3428, 0.2199, 0.3278, 0.9606],
        [0.4564, 0.3138, 0.0769, 0.9410]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [36]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [37]:
!nvidia-smi

Sun Jul 16 19:26:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti   WDDM  | 00000000:07:00.0  On |                  N/A |
| 40%   61C    P0              66W / 250W |   1074MiB / 11264MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [38]:
torch.cuda.is_available()

True

In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [42]:
tensor = torch.tensor([1,2,3])

tensor, tensor.device

tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [43]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])