## Fundamentals

In [1]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
torch.cuda.get_device_name(0)

1.11.0


'NVIDIA GeForce GTX 1080 Ti'

## Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9850, 0.3097, 0.4456, 0.4273],
        [0.8980, 0.8666, 0.6268, 0.8405],
        [0.6339, 0.7042, 0.4201, 0.1421]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
one_to_ten = torch.arange(start= 0, end= 10, step=2)

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [23]:
float_32_tensor = torch.tensor([3.0, 6.0 , 9.0], dtype = torch.float16, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_32_tensor.dtype

torch.float16

In [25]:
float_32_tensor.device

device(type='cpu')

In [26]:
tensor = torch.tensor([1, 2 ,3 ])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor = torch.tensor([1, 2 ,3 ])
tensor * 10

tensor([10, 20, 30])

In [28]:
tensor = torch.tensor([1, 2 ,3 ])
tensor - 10

tensor([-9, -8, -7])

In [29]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [30]:
# Element Wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [31]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [32]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [8,11],
                        [12,3]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8, 12],
        [ 8, 11,  3]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  30,  18],
        [ 53,  68,  48],
        [ 83, 106,  78]])

In [ ]:
x = torch.arange(0,100,10)
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
import torch 
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped = x_reshaped.squeeze()

In [ ]:
x_reshaped.unsqueeze(dim=0)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2, 0 , 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [33]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [34]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
x[0][0]

tensor([1, 2, 3])

In [36]:
x[0,0]

tensor([1, 2, 3])

In [38]:
x[0][0][1]

tensor(2)

In [39]:
x[:, : , 1]

tensor([[2, 5, 8]])

In [40]:
x[:, 1, 1]

tensor([5])

In [41]:
x[0, 0, :]

tensor([1, 2, 3])

In [42]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [44]:
x[0, 2, 2]

tensor(9)

In [46]:
import torch
import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [48]:
array = array + 1
array, tensor

(array([3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))