## Fundamentals

In [3]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
torch.cuda.get_device_name(0)

1.11.0


'NVIDIA GeForce GTX 1080 Ti'

## Tensors

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
scalar.item()

7

In [14]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [18]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])