## Fundamentals

In [47]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
torch.cuda.get_device_name(0)

1.11.0


'NVIDIA GeForce GTX 1080 Ti'

## Tensors

In [49]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [50]:
scalar.ndim

0

In [51]:
scalar.item()

7

In [52]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [53]:
vector.ndim

1

In [54]:
vector.shape

torch.Size([2])

In [55]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [56]:
MATRIX.ndim

2

In [57]:
MATRIX.shape

torch.Size([2, 2])

In [58]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [59]:
TENSOR.ndim

3

In [60]:
TENSOR.shape

torch.Size([1, 3, 3])

In [61]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8710, 0.4350, 0.1174, 0.2088],
        [0.5641, 0.7005, 0.1784, 0.7063],
        [0.2258, 0.8467, 0.9619, 0.2084]])

In [62]:
random_tensor.ndim

2

In [63]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [64]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
ones.dtype

torch.float32

In [67]:
one_to_ten = torch.arange(start= 0, end= 10, step=2)

In [68]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [69]:
float_32_tensor = torch.tensor([3.0, 6.0 , 9.0], dtype = torch.float16, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
float_32_tensor.dtype

torch.float16

In [71]:
float_32_tensor.device

device(type='cpu')

In [72]:
tensor = torch.tensor([1, 2 ,3 ])
tensor + 10

tensor([11, 12, 13])

In [73]:
tensor = torch.tensor([1, 2 ,3 ])
tensor * 10

tensor([10, 20, 30])

In [74]:
tensor = torch.tensor([1, 2 ,3 ])
tensor - 10

tensor([-9, -8, -7])

In [75]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [76]:
# Element Wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [77]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [78]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [8,11],
                        [12,3]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8, 12],
        [ 8, 11,  3]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  30,  18],
        [ 53,  68,  48],
        [ 83, 106,  78]])

In [ ]:
x = torch.arange(0,100,10)
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [79]:
x.argmin()

tensor(0)

In [80]:
x.argmax()

tensor(9)